### ISSUE TITLE
ndarray-linalg "openblas" feature does not compile on windows

### ISSUE THREAD

**Issue by TheIronBorn** [argmin-rs/modcholesky#2]
see https://github.com/blas-lapack-rs/openblas-src/issues/28

In the meantime making the `openblas` feature optional would be convenient and seems an easy fix (a single change on my machine at least)

**Comment by stefan-k** [comment]
Thanks for the suggestion! I've added optional features for all blas backends ndarray-linalg provides. I would appreciate it if you could test it on windows as I don't have a windows machine available.

**Comment by TheIronBorn** [comment]
That seems to be working well. Thanks

**Comment by stefan-k** [comment]
Thanks a lot. I've released a new version (0.1.1).

**Comment by TheIronBorn** [comment]
Parent argmin crates might need a version bump as well

**Comment by stefan-k** [comment]
Done. argmin and argmin_core are now at version 0.2.3.
